apiVersion: v1
kind: Namespace
metadata:
  name: llm-chatbot
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: llm-chatbot
  labels:
    app: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: quay.io/jkeam/simple-chatbot:latest
          imagePullPolicy: Always
          env:
          - name: MODEL_URL
            value: http://granite-predictor.llm.svc.cluster.local/v1
          ports:
          - containerPort: 8080
            name: theport
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot 
  namespace: llm-chatbot
  labels:
    app: chatbot 
spec:
  ports:
    - name: port8080
      port: 8080
      targetPort: theport
  selector:
    app: chatbot 

---    
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chatbot 
  namespace: llm-chatbot
  labels:
    app: chatbot 
spec:
  path: /
  to:
    kind: Service
    name: chatbot 
    weight: 100
  port:
    targetPort: port8080
  tls:
    termination: edge
