apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm

commonLabels:
  app: granite
  component: model

secretGenerator:
- name: model-bucket-secret
  envs:
  - .env
patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: model-bucket-secret
      labels:
        opendatahub.io/dashboard: "true"
        opendatahub.io/managed: "true"
      annotations:
        opendatahub.io/connection-type: s3
        openshift.io/display-name: Models

resources:
- namespace.yaml
- serviceaccount.yaml
- job.yaml
- servingruntime.yaml
